# Generated by Django 3.1.7 on 2021-02-27 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isomonkey', '0002_auto_20210227_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictures',
            name='image',
            field=models.BinaryField(),
        ),
    ]
