# Generated by Django 3.1.7 on 2021-03-01 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isomonkey', '0004_auto_20210227_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictures',
            name='order',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
