# Generated by Django 3.1.7 on 2021-03-01 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isomonkey', '0005_pictures_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictures',
            name='exif_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
